### ISSUE TITLE
_Sylix - Novo evento encontrado

### ISSUE THREAD

**Issue by angelobelchior** [mvpbr/Eventos#5]
RT @angelobelchior: Esse ano teremos muitos eventos bacanas #mvpbreventos :) fiquem ligados

**Comment by willbuildapps** [comment]
Tá pegando RT tb @angelobelchior =P

**Comment by angelobelchior** [comment]
E não é que funciona? ;p

**Comment by willbuildapps** [comment]
Bão demais =D
